// <auto-generated />
using System;
using MTRADashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTRADashboard.Migrations
{
    [DbContext(typeof(MTRADbContext))]
    [Migration("20250624191947_NormalizedSchema")]
    partial class NormalizedSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTRADashboard.Models.Accounting", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("AccountRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLAccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WBSCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.HasIndex("RequestID");

                    b.ToTable("Accountings");
                });

            modelBuilder.Entity("MTRADashboard.Models.Agreement", b =>
                {
                    b.Property<int>("AgreementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgreementID"));

                    b.Property<string>("AgreementNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgreementRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AgreementID");

                    b.HasIndex("RequestID");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("MTRADashboard.Models.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

                    b.Property<string>("AssetDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AssetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EquipmentNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionalLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AssetID");

                    b.HasIndex("RequestID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MTRADashboard.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryID"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SiteMapFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryID");

                    b.HasIndex("RequestID");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("MTRADashboard.Models.Employee", b =>
                {
                    b.Property<string>("EmpID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MTRADashboard.Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("MaterialCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaterialValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequestID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WPSCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialID");

                    b.HasIndex("RequestID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("MTRADashboard.Models.Request", b =>
                {
                    b.Property<string>("RequestID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("BackLoad")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByEmpID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PO_SWO_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestID");

                    b.HasIndex("CreatedByEmpID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("MTRADashboard.Models.Accounting", b =>
                {
                    b.HasOne("MTRADashboard.Models.Request", "Request")
                        .WithMany("Accountings")
                        .HasForeignKey("RequestID");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MTRADashboard.Models.Agreement", b =>
                {
                    b.HasOne("MTRADashboard.Models.Request", "Request")
                        .WithMany("Agreements")
                        .HasForeignKey("RequestID");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MTRADashboard.Models.Asset", b =>
                {
                    b.HasOne("MTRADashboard.Models.Request", "Request")
                        .WithMany("Assets")
                        .HasForeignKey("RequestID");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MTRADashboard.Models.Delivery", b =>
                {
                    b.HasOne("MTRADashboard.Models.Request", "Request")
                        .WithMany("Deliveries")
                        .HasForeignKey("RequestID");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MTRADashboard.Models.Material", b =>
                {
                    b.HasOne("MTRADashboard.Models.Request", "Request")
                        .WithMany("Materials")
                        .HasForeignKey("RequestID");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MTRADashboard.Models.Request", b =>
                {
                    b.HasOne("MTRADashboard.Models.Employee", "CreatedByEmployee")
                        .WithMany("Requests")
                        .HasForeignKey("CreatedByEmpID");

                    b.Navigation("CreatedByEmployee");
                });

            modelBuilder.Entity("MTRADashboard.Models.Employee", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("MTRADashboard.Models.Request", b =>
                {
                    b.Navigation("Accountings");

                    b.Navigation("Agreements");

                    b.Navigation("Assets");

                    b.Navigation("Deliveries");

                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
